// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcpqymcauhqiwpaashqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjcHF5bWNhdWhxaXdwYWFzaHF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTI1NTMsImV4cCI6MjA1OTYyODU1M30.wbLNai9XbsKMUPAGp-O6GVFZbWGCBBcSz3fQRH9TOzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);